feat(LERN-12): Added LoginPage
deepspace1000/learnUP pull request #50
Opened 2024-03-21 20:47 UTC by Quintexxx

2024-03-22 07:07 UTC, deepspace1000 requested changes
Nice, sometimes 3 times the same thing so really not bad

2024-03-22 07:07 UTC, deepspace1000 commented on frontend/src/customTheme.ts
> +              position: 'absolute',
if possible i would prefere no absolute positions

2024-03-22 07:07 UTC, deepspace1000 commented on frontend/src/index.css
> +  overflow-x: hidden;
why?

2024-03-22 07:07 UTC, deepspace1000 commented on frontend/src/index.css
> +  /*padding: 2rem 4rem;*/
you can delete it here maybe we can use something similar for the other pages.

2024-03-22 07:07 UTC, deepspace1000 commented on frontend/src/pages/LoginPage.tsx
> +  }
probably some ChatGPT???

2024-03-22 07:07 UTC, deepspace1000 commented on frontend/src/pages/LoginPage.tsx
> +  }
just delete the comments

2024-03-22 18:19 UTC, Quintexxx commented on frontend/src/customTheme.ts
> +              position: 'absolute',
From a CSS Standpoint not valid

2024-03-22 18:23 UTC, Quintexxx commented on frontend/src/pages/LoginPage.tsx
> +              Go back to Home
I unterstand your point of view, although the Link is very important to the integrity of the design. It gives the primarycircle a reason to be there. Without it the Left Side would look much more emtpy. This is also a reason why i was against deleting the "Password reset" Link. 

As you will see in my next Pull Request, i opted for a different Solution. The link can just go back to a simple Mail Address. This will ensure a Help Gateway for Users and give a use for the link. I hope you're satisfied with this solution

2024-03-22 18:31 UTC, Quintexxx commented on frontend/src/components/Logo.tsx
> +          <Typography sx={{ color: '#89DAD5' }}>Learn</Typography> UP
Yes i can understand your reasoning, altough i would need to disagree, this simple nesting should'nt complicate anything, another div/tag would the exact same thing. 

As for proof theres even a term for this in the joy UI Doc and they encourage to do this because the tag will be turned automatically in a span.

Proof of source:
[](https://mui.com/joy-ui/react-typography/#nested-typography)

2024-03-22 18:54 UTC, Quintexxx commented on frontend/src/components/LoginForm.tsx
> +                  borderRight: '2px solid #5EC2B7',
han jz für es ziitli mit dem divider umenand gspielt und bin ehrlich gseit nöd zfriede. Es wür mehr CSS wieder bruche de richtig anezbecho als die jetzig lösig... Ich chan scho nomal dra ane hocke aber ich bin mir sicher ob es sich lohne tuet das überarbeite

2024-03-22 18:54 UTC, Quintexxx commented on frontend/src/components/LoginForm.tsx
> +                  borderRight: '2px solid #5EC2B7',
han jz für es ziitli mit dem divider umenand gspielt und bin ehrlich gseit nöd zfriede. Es wür mehr CSS wieder bruche de richtig anezbecho als die jetzig lösig... Ich chan scho nomal dra ane hocke aber ich bin mir sicher ob es sich lohne tuet das überarbeite

2024-03-22 19:04 UTC, Quintexxx commented on frontend/src/pages/LoginPage.tsx
> +              <Typography sx={{ color: '#E191A1' }}>Log</Typography> in
Ich weis du hesch gseit du wötsch das inem component inetue allerdings gsehn ich nöd de Sinn dahinder bi eneme 3 Ziiler one time use code, du chasch mich gern alüte und mir chönd das gern bespreche.

2024-03-23 12:11 UTC, deepspace1000 commented on frontend/src/components/Logo.tsx
> +          <Typography sx={{ color: '#89DAD5' }}>Learn</Typography> UP
okay. I didn't know that. In that case nice work you already thought me something i didn't know 😆

2024-03-23 12:15 UTC, deepspace1000 commented on frontend/src/pages/LoginPage.tsx
> +              Go back to Home
okay. i think you mean commit and not pull request? If you mean commit it would be nice if you push the changes to this branch and then ask for another review because its easier for me to understand what you mean. 

To the link i get that it is important and let me know your ideas. i thought about a link to our Homepage (The website which will be with all the information and stuff). what do you think?

2024-03-23 12:18 UTC, deepspace1000 commented on frontend/src/components/LoginForm.tsx
> +                  borderRight: '2px solid #5EC2B7',
let's leave it for now. as we discussed the login page has its own kind of design which will be much simpler in the application it self so lets leave it a bit fancy 🙃

2024-03-23 15:07 UTC, deepspace1000 commented on frontend/src/pages/LoginPage.tsx
> +              Go back to Home
Will be a link to our Homepage once it exists

2024-03-23 15:08 UTC, deepspace1000 commented on frontend/src/components/LoginForm.tsx
> +                  borderRight: '2px solid #5EC2B7',
okay we will leave it here as the login page has a lot of fancy styles.

2024-03-23 15:10 UTC, deepspace1000 approved these changes
Nice 🥳

2024-03-23 15:14 UTC, merged